name: Build and Test C++ Application

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up CMake
        uses: threeal/cmake-action@v1.3.0

      - name: Set up GCC
        run: |
          sudo apt update
          sudo apt install g++-13

      - name: Build
        run: |
          cmake --build build
        env:
          CXX: g++-13

      - name: Run Tests
        run: |
          ctest --test-dir build
        env:
          CXX: g++-13